version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  | true
  # Create gtk dir for next step
  - mkdir -p AppDir/usr/share/gtk-2.0/
  # Set the default theme to Adwaita, like flatpak does
  - echo 'include "/usr/share/themes/Adwaita/gtk-2.0/gtkrc"' > AppDir/usr/share/gtk-2.0/gtkrc
  # Install chirp into the AppDir
  - git clone --depth=1 https://github.com/kk7ds/chirp | true
  - |
    cd chirp
    git pull
    LATEST_COMMIT_DATE=$(git log -1 --date=format:"%Y%m%d" --format="%ad")
    LATEST_COMMIT_SHORT=$(git rev-parse --short HEAD)
    CHIRP_VERSION="chirp-daily-${LATEST_COMMIT_DATE}+${LATEST_COMMIT_SHORT}"
    sed -i "s/CHIRP_VERSION = \".*\"/CHIRP_VERSION = \"${CHIRP_VERSION}\"/" chirp/__init__.py
    python2.7 setup.py install --prefix=/usr --root=../AppDir


AppDir:
  path: ./AppDir

  app_info:
    id: com.danplanet.chirp
    name: Chirp
    icon: utilities-terminal # FIXME
    version: 0.1.0           # FIXME
    exec: usr/bin/python2.7
    exec_args: "$APPDIR/usr/bin/chirpw $@"

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'

    include:
      - python-cairo
      - python-gobject-2
      - python-gtk2
      - python-serial
      - python-future
      - python-suds
      - python2.7
      - libxml2
      - gnome-themes-extra
      - adwaita-icon-theme
    exclude:
      - libicu60
      - humanity-icon-theme

  files:
    exclude:
      - usr/lib/x86_64-linux-gnu/gconv
      - usr/share/man
      - usr/share/doc/
      - usr/include
      - usr/share/icons/ubuntu-mono-*

  runtime:
    path_mappings:
      - /usr/share/gtk-2.0/:$APPDIR/usr/share/gtk-2.0/
    env:
      PYTHONHOME: '${APPDIR}/usr'
      PYTHONPATH: '${APPDIR}/usr/lib/python2.7/site-packages'

AppImage:
  sign-key: None
  arch: x86_64

