name: pull_request

on:
  workflow_dispatch:
  pull_request: 
    branches: ["main"]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Timezone
        run: |
          # Set timezone to America/Los_Angeles so the build date is aligned with official builds
          sudo sudo ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git python3-pip python3-setuptools patchelf fakeroot gettext
          sudo -H pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git
          arch=$(uname -m)
          sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${arch}.AppImage -O /usr/bin/appimagetool
          sudo chmod +x /usr/bin/appimagetool

      - name: Build AppImage
        run: |
          chmod +x ./build.sh
          ./build.sh
